name: Deploy

on:
  push:
    branches: [main]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Build web app
        run: npm run build

      - name: Install Functions dependencies
        run: npm ci
        working-directory: functions

      - name: Setup Firebase credentials
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy preview channel
        if: github.event_name == 'pull_request'
        run: |
          firebase hosting:channel:deploy pr-${{ github.event.number }} \
            --project "$FIREBASE_PROJECT_ID" \
            --expires 7d \
            --non-interactive

      - name: Deploy production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          firebase deploy \
            --only hosting,functions,firestore:rules,storage:rules \
            --project "$FIREBASE_PROJECT_ID" \
            --non-interactive